TITLE_1: SEP0527
TITLE_2: Empreendedores em Informática
SUBTITLE_1: Disciplina de graduação
SUBTITLE_2: Material de aula, notebooks e referências.

ABOUT: |
  Este site organiza as aulas, exercícios e material suplementar da disciplina.

REFERENCIAS: |
  <ul>
    <li>Livro A …</li>
    <li>Artigo B …</li>
  </ul>

GITHUB_LINK: https://github.com/Academic-Codex/SEP0527-Empreendedores-Em-Informatica
HERO_FILE: empreendedores-em-informatica.png